//======================================
const PrivacyPolicy = () => {
  return (
    <div className="">
      <article className="prose mx-auto max-w-4xl rounded-sm bg-gray-800 px-2 py-10 md:px-6">
        <h1>Privacy Policy</h1>
        <p>
          Our Privacy Policy ensures the protection and confidentiality of your
          personal information, emphasizing our commitment to privacy and
          security. Welcome to KamousAI (“we,” “us,” or “our”). This Privacy
          Policy outlines the practices we follow regarding the collection, use,
          and protection of your personal information when you visit our
          website. By accessing KamousAI, you agree to the terms described in
          this policy.
        </p>
        <ol>
          <li>
            Information We Collect: we do not collect any information about your
            users.
          </li>
          <li>
            Data Security:
            <li>
              <ol type="a">
                <li>
                  We implement industry-standard security measures to protect
                  your personal information from unauthorized access,
                  disclosure, alteration, and destruction.
                </li>
              </ol>
            </li>
          </li>
          <li>
            Third-Party Links:
            <ol type="a">
              <li>
                KamousAI may contain links to third-party websites. We are not
                responsible for the privacy practices or content of these
                websites. Please review the privacy policies of these third
                parties.
                <div>
                  <h3>Google Analytics</h3>
                  Our website uses Google Analytics, a web analytics service
                  provided by Google, Inc.. Google Analytics uses cookies, which
                  are text files placed on your computer, to help us to analyze
                  how visitors use the website. It also sends 3rd party requests
                  without cookies The information generated by the cookie about
                  your use of the website (including your IP address) will be
                  transmitted to and stored by Google on servers in the United
                  States. Google will use this information for the purpose of
                  evaluating your use of the website, compiling reports on
                  website activity to be looked at by Ethical Consumers, and
                  providing other services relating to website activity and
                  internet usage. Google may also transfer this information to
                  third parties where required to do so by law, or where such
                  third parties process the information on Google{"'"}s behalf.
                  Google will not associate your IP address with any other data
                  held by Google. There is a Google Analytics opt-out extension
                  for your browser here.
                </div>
              </li>
            </ol>
          </li>
          <li>
            Cookies:
            <ol type="a">
              <li>
                KamousAI uses cookies to enhance your browsing experience. You
                can manage your cookie preferences through your browser
                settings.
              </li>
            </ol>
          </li>
          <li>
            Your Choices: You have the right to opt out of receiving promotional
            communications from us by following the unsubscribe instructions
            provided in the emails.
          </li>
          <li>
            Updates to Privacy Policy We may update this Privacy Policy
            periodically. Please review the policy regularly for any changes.
          </li>
          <li>
            Contact Us: If you have questions or concerns regarding our Privacy
            Policy, please contact us at ali.hussein.pre[at]gmail.com
          </li>
        </ol>
        Thank you for trusting KamousAI. We are committed to protecting your
        privacy.
      </article>
    </div>
  );
};
export default PrivacyPolicy;
